version: "3"
services:
  bayesian-pytorch:
    container_name: bayesian-pytorch
    image: bayesian-pytorch:1.0
    build:
      context: ./docker
      dockerfile: ./Bayesian-PyTorch/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
