version: "3"
services:
  pytorch-forecasting:
    container_name: pytorch-forecasting
    image: pytorch-forecasting:1.0
    build:
      context: ./docker
      dockerfile: ./PyTorch-Forecasting/Dockerfile
      args:
        user_name: ${user_name}
        user_email: ${user_email}
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
