version: "3"
services:
  pyro:
    container_name: pyro
    image: pyro:1.0
    build:
      context: ./docker
      dockerfile: ./Pyro/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
